### ISSUE TITLE
dev: add state bridge contract for Linea

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#1]
# Add State Bridge Contract for Linea

## Objective
Implement a State Bridge contract for Linea to enable secure propagation of Merkle roots from the main World ID Identity Manager on Ethereum to the World ID contract on Linea L2.

## Tasks
1. Research Linea's L1<>L2 messaging system, including:
   - Ownership model
   - Gas fee handling
   - Message passing mechanisms
2. Implement a `LineaStateBridge` contract on Ethereum.
3. Develop functionality to propagate Merkle roots to the World ID contract on Linea.

## Implementation Details
- Use [OpStateBridge.sol](https://github.com/worldcoin/world-id-state-bridge/blob/main/src/OpStateBridge.sol) from the [world-id-state-bridge](https://github.com/worldcoin/world-id-state-bridge/) repository as a reference.
- Implement or adapt a mechanism similar to Optimism's `CrossDomainOwnable` to ensure that only the `LineaStateBridge` contract on Ethereum can update the World ID contract on Linea.
- Ensure proper handling of gas fees for cross-chain message passing.

## Acceptance Criteria
- [ ] `LineaStateBridge` contract is implemented and compiles successfully.
- [ ] Contract can securely propagate Merkle roots from Ethereum to Linea.
- [ ] Ownership and permission system is implemented to prevent unauthorized updates.
- [ ] Gas fee handling is properly implemented for cross-chain messages.
- [ ] Contract passes all relevant tests.
- [ ] The contract is properly documented to reflect its functionality

## Resources
- [OpStateBridge.sol](https://github.com/worldcoin/world-id-state-bridge/blob/main/src/OpStateBridge.sol)
- [Linea Documentation](https://docs.linea.build/developers/quickstart)

**Comment by DevPelz** [comment]
hello, can i work o this, i have experience in building smart contracts and auditing them as well so i can build this.

**Comment by Ugo-X** [comment]
Hello Project Lead! I'm Ugo, a fullstack Solidity dev(js,React,Node,Next.js,Three.js, solidity) developer with a strong track record in OD hack projects. I've been actively involved since Edition 2, contributing to various initiatives, and I'm thrilled to be part of Edition 5!
Having used OnlyDust extensively (see my profile: https://app.onlydust.com/)), I'm confident in my ability to tackle new challenges within this edition.
I'm eager to leverage my skills and experience to contribute effectively.

I am experienced with working on such issues and would love to contribute effectively to this project

**Comment by KodeSage** [comment]
Hi @kfastov , I would love to take up this tasks and work on it.
I have experience in writing solidity and I have worked and Contributed to top projects.

**Comment by kfastov** [comment]
Hey @KodeSage ! Good luck with it!

**Comment by 0xprinc** [comment]
Hey @KodeSage, I've been assigned issue #2, where I need to implement the `LineaWorldID` contract. This contract will receive cross-chain messages sent by the `LineaWorldState` contract, which I understand you're working on.
Could you please let me know which bridging method from the Linea documentation you're using? This will help me ensure that my contract is compatible.

**Comment by KodeSage** [comment]
Hey Burvv @0xprinc  @0xprinc , you should look at the Messaging Service in Linea. https://docs.linea.build/architecture/stack/canonical-msg-service/message-service#interface-imessageservicesol


I would push up very soon so you can check out my implementations.

**Comment by KodeSage** [comment]
<img width="864" alt="Screenshot 2024-06-23 at 19 11 56" src="https://github.com/kfastov/worldcoin-bridge-linea/assets/40062598/300ff769-0b37-408e-ad8c-e1b900abc830">


you should also check out this workflows too @0xprinc

**Comment by DevPelz** [comment]
Hello @kfastov, I attempted to send you a DM on Telegram but was unable to reach you. I would love to discuss how my auditing services could benefit your team. If you're interested, please reach out to me on Telegram @Pelumi_Al. I’d be happy to share my portfolio and discuss further.

Thank you!

**Comment by kfastov** [comment]
The issue is solved now, thank you @KodeSage !
