### ISSUE TITLE
Deploy and test the bridge on testnet against real Worldcoin contracts

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#23]
### Description

Deploy the bridge on the testnet and test it against real Worldcoin contracts that are already deployed there.

### Tasks

1. Deploy the `LineaStateBridge` on Ethereum Sepolia.
2. Deploy the `LineaWorldID` on Linea Sepolia, setting the authorized sender to `LineaStateBridge` on L1.
3. Test the cross-layer operation by propagating the root from `WorldIDIdentityManager` on Ethereum Sepolia to `LineaWorldID` on Linea Sepolia, and querying it later on L2 (you may need to figure out how those roots are used on other L2s to send meaningful calls).
4. Encapsulate all these actions into a script that anyone can run (providing it with pre-funded accounts on Ethereum and Linea testnets).

### Acceptance Criteria

- [ ] LineaStateBridge is deployed on Ethereum Sepolia.
- [ ] LineaWorldID is deployed on Linea Sepolia with the authorized sender set to LineaStateBridge.
- [ ] Successful cross-layer operation by propagating the root from WorldIDIdentityManager on Ethereum Sepolia to LineaWorldID on Linea Sepolia.
    - [ ] Transaction hashes of the corresponding transactions should be posted into the issue or PR comment.
- [ ] A script is provided that can automate all the deployment and testing steps, using pre-funded accounts on Ethereum and Linea testnets.

### Caveats

- You may need to figure out how the roots are used on other L2s to send meaningful calls.
- Ensure the script can handle pre-funded accounts on both Ethereum and Linea testnets for seamless operation.

### Resources

- https://github.com/worldcoin/world-id-state-bridge - may contain some clues on how the bridge can be deployed on testnet

**Comment by adrianvrj** [comment]
hi, can I work on this?

**Comment by Immanuelolivia1** [comment]
Hi @kfastov i have worked on something similar to this before and would love to hop on this

**Comment by zarah-s** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
With my strong background in Rust, Solidity and JavaScript, I can apply my expertise in solving this issue

**Comment by BenFaruna** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hello, my name is Benjamin Faruna and I am software engineer with experience writing and deploying smart contracts on EVM compatible chains.

### How I plan on tackling this issue
- I would study the contract and understand the constructor arguments that are required for deployment.
- Write script to deploy contract and ensure the script work in a local development environment.
- Check everything works with the caveats given
- Once the script is confirmed to be working as intended, I will use the script to deploy the contracts to Ethereum sepolia and Linea sepolia.

**Comment by TropicalDog17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hi team,
I'm a software engineer who have experience in Solidity and has helped with many open source projects.. I want to contribute and complete the issue to ensure correct functionality for the Worldcoin Bridge.

### How I plan on tackling this issue
First, I will take an overview look at the repository and understand how the bridge works. Then I will follow the steps given in the issue and make sure my deliverable passes all acceptance criteria.

**Comment by Ugo-X** [comment]
Hello Project Lead! I'm Ugo, a fullstack blockchain Dev (js,React,Node,Next.js,Three.js, Cairo, solidity) developer with a strong track record in OD hack projects. I've been actively involved since Edition 1, contributing to various initiatives, and I'm thrilled to be part of Edition 6!
Having used OnlyDust extensively (see my profile: https://app.onlydust.com/u/Ugo-X)), I'm confident in my ability to tackle new challenges within this edition.
I'm eager to leverage my skills and experience to contribute effectively.

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hi, 

I'm Alvaro Lazarus, a Software Engineer diving into blockchain technologies. I'm experienced with Typescript, Python, Solidity and JavaScript. Really looking forward to gaining more experience by working on projects like this.

### How I plan on tackling this issue
My approach:

•  Read through the resources to familiarize with the project and how the bridge works
•  Write the Script making sure it can handle pre-funded accounts
•  Test the Script to ensure it can automate all the deployment and testing steps

I'm reeeally excited to contribute to this project, and I look forward to hearing back from you.

Best regards,
Lazarus

**Comment by Abhi270303** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hi, I am a Solidity developer, I prefer Foundry framework for testing smart contracts, I have decent experience in Writing Deploy Scripts for contracts and also Write Unit tests for testing contracts. I have also done Stateless fuzz testing. I always try to maintain the code quality so that it is easier for developers to understand the code. I believe my background can be leveraged to contribute to Worldcoin-bridge-linea.

### How I plan on tackling this issue
I will make a folder for scipts, Two files will be included `DeployBridge.s.sol` & `HelperConfig.s.sol`. DeployBridge would be having Deploy Scripts inside & HelperConfig will be consisting of LocalAnvilEth Config, SepoliaEthConfig & SepoliaLineaConfig for easily deploying contracts, after that I will write tests in test folder , In tests there will be setUp and Tests for each functionality of bridge to test if it is working properly, and forge coverage will give me idea of how much codebase I have covered.

**Comment by bitfalt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hi! I'm Daniel a software developer with previous contributions to the ODHack. I've dealt with Solidity in a course I'm taking to further enhance my skills, as well as the platform NodeGuardians (see my profile here: https://nodeguardians.io/character/bitfalt). I've successfully deployed a L2 using the OPStack, which involved syncing the state of my L2 to L1. You can see my tweet of successfully doing this in my Twitter profile (https://x.com/bitfalt). 

### How I plan on tackling this issue
My approach to the problem would be the following:
- I would read the provided resource on how to successfully deploy the bridge on testnet
- Deploy the LineaWorldID on Linea Sepolia fulfilling the specified requirements
- Investigate how the roots are used to make meaningful calls and create the cross-layer operation
- I'll investigate how would the script handle pre-funded accounts on both testnets.
- I'll documment my whole process while doing it manually, once I've tested everything manually. I'll start making the script to automate all the steps.
- Additionally, I will make the necessary testing to ensure proper behaviour.

**Comment by TropicalDog17** [comment]
Hi @kfastov,
I'm encountering an issue while attempting to deploy the contracts. It appears there's a circular dependency in the deployment process, as both LineaStateBridge and LineaWorldID require each other's address.
I'm working on a solution in #28, but I'm running into a problem when trying to call transferOwnershipLinea: https://github.com/kfastov/worldcoin-bridge-linea/pull/28/files#diff-904caeb0278f99dbfc4fa78851a47c89e46f70cacea7619a87c1fe7c6de193cfR32. It seems the function call is failing. Thank you for your help!

```
Traces:
  [1050552] → new InitializeLineaStateBridge@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    ├─ [0] VM::projectRoot() [staticcall]
    │   └─ ← [Return] "/home/tropicaldog17/personal/worldcoin-bridge-linea"
    ├─ [0] VM::readFile("src/script/.deploy-config.json") [staticcall]
    │   └─ ← [Return] <file>
    └─ ← [Return] 3109 bytes of code

  [108028] InitializeLineaStateBridge::setUp()
    ├─ [0] VM::parseJson("<JSON file>", ".lineaStateBridgeAddress") [staticcall]
    │   └─ ← [Return] <encoded JSON value>
    ├─ [0] VM::parseJson("<JSON file>", ".lineaWorldIDAddress") [staticcall]
    │   └─ ← [Return] <encoded JSON value>
    ├─ [0] VM::parseJson("<JSON file>", ".messageServiceAddress") [staticcall]
    │   └─ ← [Return] <encoded JSON value>
    └─ ← [Stop] 

  [31117] InitializeLineaStateBridge::run()
    ├─ [0] VM::envUint("PRIVATE_KEY") [staticcall]
    │   └─ ← [Return] <env var value>
    ├─ [0] VM::startBroadcast(<pk>)
    │   └─ ← [Return] 
    ├─ [15577] MetaMultiSigWallet::transferOwnershipLinea(TransparentUpgradeableProxy: [0x971e727e956690b9957be6d51Ec16E73AcAC83A7], MetaMultiSigWallet: [0x88CD2e6602E5Be22b61F8e2a99d245E66A8F6406])
    │   ├─ [7335] TransparentUpgradeableProxy::sendMessage(0xA1b74396CaC8D72473632f80c511fDdD2E81144e, 1000000 [1e6], 0xc903b062000000000000000000000000971e727e956690b9957be6d51ec16e73acac83a700000000000000000000000088cd2e6602e5be22b61f8e2a99d245e66a8f6406)
    │   │   ├─ [144] L2OnL1Recovery::sendMessage(0xA1b74396CaC8D72473632f80c511fDdD2E81144e, 1000000 [1e6], 0xc903b062000000000000000000000000971e727e956690b9957be6d51ec16e73acac83a700000000000000000000000088cd2e6602e5be22b61f8e2a99d245e66a8f6406) [delegatecall]
    │   │   │   └─ ← [Revert] EvmError: Revert
    │   │   └─ ← [Revert] EvmError: Revert
    │   └─ ← [Revert] EvmError: Revert
    └─ ← [Revert] EvmError: Revert
```

**Comment by kfastov** [comment]
@TropicalDog17 I've missed your message due to notification problem on my side, sorry for that. I am investigating the problem now.

**Comment by kfastov** [comment]
@TropicalDog17
I've only tested this script on Anvil and got an error for an obvious reason (because Anvil doesn't have the Linea messaging service and stuff). But I see extra logs in your comment which means you ran the script properly. Please share how did you run the script to get this error.

**Comment by TropicalDog17** [comment]
> @TropicalDog17 I've only tested this script on Anvil and got an error for an obvious reason (because Anvil doesn't have the Linea messaging service and stuff). But I see extra logs in your comment which means you ran the script properly. Please share how did you run the script to get this error.

Hi, I adapted the original deploy process here: https://github.com/worldcoin/world-id-state-bridge

### Prequiste

 There should be `.env` file on project root that contain private key of the test account, and also a `.deploy-config.json` file that contains address of contract, which is filled along the way I deploy(should be automated, but for now I am doing all this manually)

Something like this(deployed contracts on Ethereum and Linea Sepolia)
```{
  "worldIDIdentityManagerAddress": "0x928a514350A403e2f5e3288C102f6B1CCABeb37C",
  "lineaStateBridgeAddress": "0x88CD2e6602E5Be22b61F8e2a99d245E66A8F6406",
  "messageServiceAddress": "0x971e727e956690b9957be6d51Ec16E73AcAC83A7",
  "lineaWorldIDAddress": "0xA1b74396CaC8D72473632f80c511fDdD2E81144e"
}
```

### Deployment process
I first deployed the `LineaWorldID` on Linea Sepolia
`forge script src/script/DeployLineaWorldID.s.sol:DeployLineaWorldID --fork-url https://rpc.sepolia.linea.build	 --chain-id 59141 --broadcast`

+ It is initialized using a dummy `LineaStateBridge`, because not deployed yet.
![image](https://github.com/user-attachments/assets/10d522a5-4a18-493b-84b2-390f2c559f56)


+ Update the `LineaWorldID` contract address to the `.deploy-config.json`, then we deploy the `LineaStateBridge`, using this command: `forge script src/script/DeployLineaStateBridge.s.sol:DeployLineaStateBridge --fork-url  https://rpc-sepolia.rockx.com --broadcast`

After that both `LineaWorldID` and `LineaStateBridge` are deployed.

-> I attempt to change the remote sender value of `LineaWorldID` to the newly deployed  `LineaStateBridge` but not work and get the above error instead.

**Comment by kfastov** [comment]
I tried to replicate the whole process and I think I understand why it doesn't work. For the simplicity I'll repeat the deploy whole deploy process here:
1) Deploy `LineaWorldID` on L2 with dummy `remoteSender` address
2) Deploy `LineaStateBridge` on L1 with real `LineaWorldID` address
3) Call `transferOwnership` on `LineaStateBridge`, setting `remoteSender` to the address of deployed `LineaStateBridge`
This wouldn't work for two reasons.
- The first one is because the call goes to the messageService address on L2 (0x971e727e956690b9957be6d51Ec16E73AcAC83A7), not on L1 (0xB218f8A4Bc926cF1cA7b3423c154a0D627Bdb7E5 on Sepolia).
- But even if we fix it, LineaWorldID would reject this call because it requires the sender address to match configured `remoteAddress`, and we can't achieve it. Looks like a flow in contract design, and I guess it's already fixed in the "second" version where we migrated the contracts to `CrossDomainOwnable` (we can deploy `LineaWorldID` with "local" owner and then set the owner to `LineaStateBridge` contract on L1)
