### ISSUE TITLE
dev: Determine typical gas limits for relaying messages to Linea

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#3]
### Description

We need to calculate and set appropriate gas limits for relaying messages from Ethereum to Linea in our World ID State Bridge contract.

### Tasks

1. Find a method to calculate gas needed for relaying messages from Ethereum to Linea.
2. Estimate gas limits required for each type of message sent from the state bridge on Ethereum to the World ID contract on Linea.
3. Modify the [LineaStateBridge](https://github.com/kfastov/worldcoin-bridge-linea/blob/main/src/LineaStateBridge.sol) contract to include default gas limits for each message type.

### Acceptance Criteria

- [ ] Gas calculation method is documented
- [ ] Gas estimates for each message type are provided and justified.
- [ ] [LineaStateBridge](https://github.com/kfastov/worldcoin-bridge-linea/blob/main/src/LineaStateBridge.sol) contract is updated with appropriate gas limit constants or variables.
- [ ] Code changes are thoroughly tested and reviewed.

### Resources

- [Linea Documentation](https://docs.linea.build/)

**Comment by josephchimebuka** [comment]
I would like to hop on this

**Comment by aguzmant103** [comment]
Hi @kfastov also would love to take this one!

**Comment by Ugo-X** [comment]
Hello Project Lead! I'm Ugo, a fullstack Solidity dev(js,React,Node,Next.js,Three.js, solidity) developer with a strong track record in OD hack projects. I've been actively involved since Edition 2, contributing to various initiatives, and I'm thrilled to be part of Edition 5!
Having used OnlyDust extensively (see my profile: https://app.onlydust.com/)), I'm confident in my ability to tackle new challenges within this edition.
I'm eager to leverage my skills and experience to contribute effectively.

I am experienced with working on such issues and would love to contribute effectively to this project

**Comment by kfastov** [comment]
@Ugo-X good luck!
