### ISSUE TITLE
tests: Implement end-to-end tests for the entire World ID state bridge system

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#4]
### Description

You need to create comprehensive end-to-end tests for the entire World ID state bridge system. to ensure that all components work together correctly and that the cross-chain functionality operates as expected.

### Tasks

1. Look up the best practices of how cross-domain messaging is tested on Linea (see [linea-contracts](https://github.com/Consensys/linea-contracts) repo, any other repos and sources that may be helpful)
2. Write automated tests for our bridge according to those best practices. They should cover all basic functionality: initialization of both contracts, propagating roots from L1 using `LineaStateBridge`, receiving and processing those roots on L2 with `LineaWorldID` contract
3. Test various scenarios, including:
   - Normal operation (successful state updates by authorized senders)
   - Edge cases (e.g., fraud updates from unauthorized addresses)

### Acceptance Criteria

- [ ] Tests cover all major components and their interactions.
- [ ] All methods of `LineaStateBridge` and `LineaWorldID` are covered by tests
- [ ] Both success and failure scenarios are tested.
- [ ] All tests pass consistently (it's fine for tests to fail if you detect bugs in our contracts while writing these tests)

### Caveats

- You may need to write a [simple] mock for the WorldIDIdentityManager (its latestRoot() method is used for receiving Merkle tree roots that are propagated to L2)
- I don't yet know how to test L1->L2 interaction, you should be able to figure it out yourself and come up with a good way of doing it (please provide a good explanation of your choice)

### Resources

- [Foundry Testing Documentation](https://book.getfoundry.sh/forge/writing-tests)
- [Linea contracts repo](https://github.com/Consensys/linea-contracts)

**Comment by Immanuelolivia1** [comment]
I would like to work on this

**Comment by pope-h** [comment]
For testing would you require forking the mainnet or is foundry test enough? @kfastov

**Comment by gidson5** [comment]
Can I take this on?

**Comment by kfastov** [comment]
@pope-h @gidson5 Could you please also leave a message in Telegram? If you already did it and your TG username is different than on Github, please send me your Github username on TG

**Comment by kfastov** [comment]
@pope-h I think Foundry tests are enough here, if they cover the entire flow of both contracts. Other parts, like World ID identity contract can be mocked. Then, we can deploy everything to testnet and integrate with existing Worldcoin contracts there, but maybe I'll create a separate task for it.

**Comment by MukulKolpe** [comment]
Hello @kfastov,

I am a full-stack developer with extensive experience in various open-source projects. I am excited about the opportunity to contribute and would love to work on this issue during ODHack 5.0. I have significant expertise in Solidity, including writing comprehensive test suites with high coverage, as well as performing invariant and fuzz testing.

Here is a link to my OnlyDust profile: https://app.onlydust.com/u/MukulKolpe

**Comment by vmmuthu31** [comment]
Hyy, @kfastov. I’m interested in this task.

**Comment by gidson5** [comment]
> @pope-h @gidson5 Could you please also leave a message in Telegram? If you already did it and your TG username is different than on Github, please send me your Github username on TG

Hy @kfastov i already left you a message on TG

**Comment by kfastov** [comment]
@MukulKolpe Hi! Unfortunately, the ODHack is over, and I am not sure this issue can be rewarded right now, but if you like, you may still take it 😄

**Comment by kfastov** [comment]
@MukulKolpe Hi! The PRs for the contracts are already merged, so you can now finally test the actual contracts

**Comment by MukulKolpe** [comment]
Perfect, I'll have the draft PR ready soon.

**Comment by kfastov** [comment]
Hi @MukulKolpe ! Can you please share your progress on this issue?

**Comment by kfastov** [comment]
Sorry @MukulKolpe  I don't want somebody to duplicate your work, but I'll have to assign this issue to someone else to get it done

**Comment by Jemiiah** [comment]
can I get on this issue @kfastov

**Comment by MukulKolpe** [comment]
Hi @kfastov, I apologize for the delay; I got caught up with some work. Please feel free to assign it to someone else.

**Comment by kfastov** [comment]
@MukulKolpe No problem at all, thank you for the update. Please feel free to return whenever you have time

**Comment by zarah-s** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
With my strong background in Rust, Solidity and JavaScript, I can apply my expertise in solving this issue

**Comment by DevSwayam** [comment]
I would like to work on this issue. I am applying via OD Hacks.

**Scope:**  
This issue has been assigned as medium difficulty but could also be considered high difficulty.

**Why high difficulty?**  
The contract needs to be tested with _**stateless and stateful fuzzing**_ tests to ensure it can handle edge cases for both unit and integration tests.

**Why me?**  
I am well-suited for this work. I know how to perform integration, unit, and stateful/stateless fuzzing. I can also use static analysis tools to find bugs and provide a comprehensive audit report that will be valuable in the long term. Additionally, I am capable of writing code for migrating and resolving issues.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
I'm a web3 blockchain developer who have experience interacting with solidity and Cairo codes and would be able to tackle the issue 

### How I plan on tackling this issue
Review the documentation and code examples in the Linea contracts repository.
 • Look for any testing frameworks or strategies they use for cross-domain messaging.
 • Study other repositories or documentation related to cross-chain communication, such as those from projects like Polkadot, Cosmos, or similar.

Use a testing framework like Foundry or Hardhat.
 • Write test scripts that:
 • Deploy the LineaStateBridge and LineaWorldID contracts.
 • Initialize the contracts and verify their initial states.
 • Simulate cross-chain messages by propagating roots from L1 using LineaStateBridge and receiving them on L2 using LineaWorldID.
 • Include assertions to verify that the state transitions occur as expected.

**Comment by Abhi270303** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hi, I am a Solidity developer, I prefer Foundry framework for testing smart contracts, I have decent experience in Writing Deploy Scripts for contracts and also Write Unit tests for testing contracts. I have also done Stateless fuzz testing. I always try to maintain the code quality so that it is easier for developers to understand the code. I believe my background can be leveraged to contribute to Worldcoin-bridge-linea.

### How I plan on tackling this issue
I will make a folder for scipts, Two files will be included DeployBridge.s.sol & HelperConfig.s.sol. DeployBridge would be having Deploy Scripts inside & HelperConfig will be consisting of LocalAnvilEth Config, SepoliaEthConfig & SepoliaLineaConfig for easily deploying contracts, after that I will write tests in test folder , In tests there will be setUp and Tests for each functionality of bridge to test if it is working properly, and forge coverage will give me idea of how much codebase I have covered.

**Comment by DIWAKARKASHYAP** [comment]
i want to work on this issue
