### ISSUE TITLE
Support setting default values for Deploy config

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#40]
### Description

We need to implement a system for managing default configuration values for our deployment process. This will improve consistency and ease of use across different environments.

### Tasks:
1. Create default config files for each environment (e.g., mainnet, sepolia) with important default values such as:
   - World Identity contract address
   - Message Service contract address
   - Other relevant contract addresses or parameters

2. Implement a mechanism to copy the appropriate default config file to the location of the main config file when it doesn't exist.

3. Modify the deploy script to initialize the main config using the default values when started.

### Acceptance Criteria:
- [ ] Default config files are created for each environment (at least mainnet and sepolia)
- [ ] A system is in place to copy the appropriate default config when the main config doesn't exist
- [ ] The deploy script correctly initializes using the default config values

This enhancement will streamline our deployment process and ensure consistent configuration across different environments.

**Comment by Jemiiah** [comment]
I would love to work o this issue

**Comment by kateberryd** [comment]
Hi

**Comment by Gift-Naomi** [comment]
Hi

**Comment by lordshashank** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
I have been working on blockchain domain and have made various dapp pilpelines and deployed them to production as well.

### How I plan on tackling this issue
I would define the default values of config and make them initalize while running if they are not specified as per the network helping in streamlining the process.

**Comment by kateberryd** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hi @kfastov Please can I be assign this issue


### How I plan on tackling this issue

To address the issue, I would create separate configuration files for each environment (sepolia, mainet) and store the corresponding deployment values. Then, I would implement a system that:

Copies the appropriate default config file to the main config file location if it doesn't already exist.
Modifies the deployment script to initialize the main config file using the values from the respective environment's configuration file.
This approach allows for easy switching between environments and ensures that the correct configuration values are used for each deployment

**Comment by KodeSage** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
I'm A Software Engineer with Solid Background in the Web3 Space. Experienced in writing Solidity and have contributed to projects too.

### How I plan on tackling this issue
1. I will create a separate JSON files for each environment (e.g., mainnet, sepolia) containing the default configuration values. These files should include essential contract addresses and any other parameters needed for deployment.

2. In my deployment script, I will add logic to check if the main config file exists for the target environment. If it doesn't, the script should copy the appropriate default config file to the location of the main config file.

3. I will Ensure that the deploy script is configured to initialize using the values from the main config file. If the main config file was copied from a default config, it will automatically have the appropriate default values.

4. I will Ensure that the script runs correctly by testing it in different environments. For example:
- Delete or move the main config file and run the deploy script to confirm that it uses the default values.
- Confirm that the script doesn’t overwrite existing config files if they already exist.

**Comment by kfastov** [comment]
@lordshashank 
Hey! Please use these values for the addresses:
Testnet (Sepolia):
```
{
    "worldIDIdentityManagerAddress": "0xb2ead588f14e69266d1b87936b75325181377076",
    "messageServiceAddressL1": "0xB218f8A4Bc926cF1cA7b3423c154a0D627Bdb7E5",
    "messageServiceAddressL2": "0x971e727e956690b9957be6d51Ec16E73AcAC83A7",
}
```
Mainnet:
```
{
    "worldIDIdentityManagerAddress": "0x163b09b4fE21177c455D850BD815B6D583732432",
    "messageServiceAddressL1": "0xd19d4B5d358258f05D7B411E21A1460D11B0876F",
    "messageServiceAddressL2": "0x508Ca82Df566dCD1B0DE8296e70a96332cD644ec",
}
```
Reference:
https://docs.worldcoin.org/reference/address-book
https://docs.linea.build/architecture/stack/canonical-msg-service/message-service

**Comment by DIWAKARKASHYAP** [comment]
i want to work on this issue
