### ISSUE TITLE
Create L2 monitor for Anchor events

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#44]
### Description

Develop a JavaScript module that listens to `L1L2MessageHashesAddedToInbox` events on Linea (L2) for messages processed by L2MessageService and LineaWorldID. This module will identify and output known message hashes, facilitating the monitoring of root propagation on L2.

### Tasks

1. Set up necessary dependencies (ethers.js, Linea SDK if required)
2. Create a new JavaScript file for the L2 event listener
3. Implement function to connect to Linea network and set up event listeners. It should take contract addresses and Linea endpoint, and also an array of known message hashes as parameters
4. Develop logic to process `L1L2MessageHashesAddedToInbox` events and extract message hashes
5. Implement console logging for known message hashes

### Acceptance Criteria

- [ ] Module listens to `L1L2MessageHashesAddedToInbox` events on Linea
- [ ] Known message hashes are correctly identified and logged to console
- [ ] Module accepts Linea endpoint, L2MessageService, and LineaWorldID addresses as arguments
- [ ] Code is well-documented and follows best practices

### Resources

- [Example transaction with L1L2MessageHashesAddedToInbox event](https://sepolia.lineascan.build/tx/0x80422ec16ea8cd0517fef7f99fb79e1f4e0b4279a1cc9d045b952c011ff137b8#eventlog)
- [ethers.js Documentation](https://docs.ethers.org/v6/)
- [Linea SDK Documentation](https://docs.linea.build/developers/guides/linea-sdk)

**Comment by EjembiEmmanuel** [comment]
@

**Comment by ShantelPeters** [comment]
Can I work on this ?

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hey, I am ikem Peter. a fullstack software developer with 3+ years of working experience, I would love to help out with this issue...

**Comment by fishonamos** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Backend developer

### How I plan on tackling this issue
I will create a JavaScript module using ethers.js to listen for L1L2MessageHashesAddedToInbox events on Linea (L2). Next, I will identify known message hashes, and log them.

**Comment by EjembiEmmanuel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
@kfastov can I hop on this issue? I'm an experienced JavaScript Developer

### How I plan on tackling this issue
- Installing necessary dependencies
- Create a JS file for the event listener
- Implement function to connect to Linea network and set up event listeners 

```JavaScript
async function setupEventListeners(contractAddresses, knownMessageHashes) {
  try {
    // Get contract instances
    const l2MessageService = new ethers.Contract(contractAddresses.l2MessageService, abi, provider);
    // Initialize other contracts if needed

    // Listen for L1L2MessageHashesAddedToInbox events
    l2MessageService.on('L1L2MessageHashesAddedToInbox', (root, messageHashes) => {
      messageHashes.forEach((hash) => {
        if (knownMessageHashes.includes(hash)) {
          //  logic to process L1L2MessageHashesAddedToInbox events and extract message hashes       
         }
      });
    });

    console.log('Event listener set up successfully.');
  } catch (error) {
    console.error('Error setting up event listener:', error);
  }
}
```

**Comment by estherbreath** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hi
I am a Blockchain developer, very swift with Javascript and Web3 frontend.

My expertise in JavaScript and Web3 frontend development positions you perfectly to tackle this issue. By leveraging my skills, I can efficiently set up a JavaScript module that connects to the Linea network, listens for L1L2MessageHashesAddedToInbox events, and identify known message hashes. My familiarity with Web3.js will enable me to interact with smart contracts and process blockchain events smoothly, ensuring the module meets all acceptance criteria while adhering to best coding practices.



### How I plan on tackling this issue
Below are the summary of how I’m going o tackle this issue.

    • Create the Module File: Make a new JavaScript file dedicated to the event listener logic. 
    • Connect to Linea Network: Write a function in the file that connects to the Linea network using the provided endpoint. This function will also set up event listeners for the L1L2MessageHashesAddedToInbox events on the specified contracts. 
    • Listen for Events: Implement the logic to listen for these events, extract message hashes, and compare them with known hashes. Log any matches to the console. 
    • Test and Document: Test the module thoroughly to ensure it works as expected.
