### ISSUE TITLE
Develop claimMessage functionality for pending messages

### ISSUE THREAD

**Issue by kfastov** [kfastov/worldcoin-bridge-linea#45]
### Description

Create a JavaScript module that calls the `claimMessage` function on L2MessageService using ethers.js and the Linea SDK. This module will facilitate the claiming of pending messages on L2.

### Tasks

1. Set up necessary dependencies (ethers.js, Linea SDK)
2. Create a new JavaScript file for the claimMessage functionality
3. Implement the main function to call `claimMessage` on L2MessageService
4. Add secure handling for the private key from an environment variable
5. Implement error handling and logging

### Acceptance Criteria

- [ ] JavaScript module successfully calls `claimMessage` on L2MessageService
- [ ] Module accepts message hash, nonce, calldata, and L2MessageService address as arguments
- [ ] Private key is securely read from an environment variable
- [ ] Proper error handling and logging are implemented
- [ ] Code is well-documented and follows best practices

### Caveats

- Ensure the private key is never logged or exposed
- Consider gas price fluctuations and implement a mechanism to handle failed transactions

### Resources

- [ethers.js Documentation](https://docs.ethers.org/v6/)
- [Linea SDK Documentation](https://docs.linea.build/developers/guides/linea-sdk)
- [Example of calling claimMessage](https://sepolia.lineascan.build/tx/0x0fddab24d1d22f3454d20e2ed79297015f67bbb401541d2012494ec5edaabfa0)

**Comment by Jemiiah** [comment]
b

**Comment by od-hunter** [comment]
N

**Comment by ikemHood** [comment]
h

**Comment by ooochoche** [comment]
Hi

**Comment by ShantelPeters** [comment]
Hi @kfastov please can I be assigned to this

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
As an experienced Full Stack Blockchain Developer, I'm excited to contribute my expertise to Edition 7 of the OnlyDust hackathons. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Solidity, and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 28 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we embark on Edition 7, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
With a passion for creating cutting-edge solutions, I'm excited to collaborate with the OnlyDust community and contribute to the advancement of the blockchain ecosystem.


### How I plan on tackling this issue
I will import the necessary dependencies (ethers and L2MessageService from @lineaprotocol/sdk) at the beginning of the file.
I will define the claimMessage function, which takes the required parameters (messageHash, nonce, callData, l2MessageServiceAddress, and privateKey).
Inside the claimMessage function:
 I will create an Ethereum provider using the ethers.providers.JsonRpcProvider class, connecting to the Linea node.
 I will create an instance of the L2MessageService contract using the provided l2MessageServiceAddress.
 I will load the Ethereum wallet using the provided privateKey.
 I will call the claimMessage function on the L2MessageService contract, passing the messageHash, nonce, and callData as arguments, and setting the appropriate gas limit and gas price.
 I will wait for the transaction to be mined using the tx.wait() method.
 I will log the successful transaction details.
 I will return the transaction receipt.
I will wrap the entire function in a try-catch block to handle any errors that may occur, and I will log the error and rethrow it.
I will export the claimMessage function for use in other parts of the application.

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hey, I am ikem Peter. a fullstack software developer with 3+ years of working experience, I would love to help out with this issue...

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
I would love to work on this issue @kfastov 
I made contribution to many repositories and merged including this one and would still love to work on this issue and continue in the partnership that has long started 


### How I plan on tackling this issue
1. Install the required dependencies, ethers.js and the Linea SDK, using a package manager like npm or yarn.
2. Create a new file, e.g., messageClaimManager.js to house the claimMessage functionality.
3. Create an async function that will handle the claimMessage operation.
4. Use the Linea SDK to interact with the L2MessageService contract.
5. Implement the logic to call the claimMessage function, passing the necessary parameters.
6. Handle any return values or events emitted by the claimMessage function.
7. Store private keys using env , ensuring it is stored securely and not exposed in the codebase.
8. Add proper error handling to the claimMessage function, ensuring that any issues with the Ethereum connection, contract interaction, or other errors are gracefully handled.
9. Implement logging mechanisms to track the execution of the claimMessage function and any errors that may occur.

Here how i would implement this :

      // messageClaimManager.js
      const { ethers } = require('ethers');
      const { LineaProvider, LineaWallet } = require('@lineaprotocol/sdk');

      async function claimMessage(messageId) {
      try {
     // Retrieve the private key from an environment variable
    const privateKey = process.env.PRIVATE_KEY;

    // Create a wallet instance using the private key
    const wallet = new ethers.Wallet(privateKey);

    // Create a Linea provider and wallet instance
    const provider = new LineaProvider('https://rpc.linea.build');
    const lineaWallet = new LineaWallet(wallet, provider);

    // Get the L2MessageService contract instance
    const l2MessageServiceContract = await lineaWallet.getContract(
      'L2MessageService'
    );

    // Call the claimMessage function on the L2MessageService contract
    const txResponse = await l2MessageServiceContract.claimMessage(messageId);
    await txResponse.wait();

    console.log(`Message ${messageId} claimed successfully.`);
    
    } catch (error) {
    console.error(`Error claiming message ${messageId}:`, error);
    }
    }

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hello, I'll like to be assigned to work on this. I am a first time contributor and would love to be given the opportunity.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
I am Benjamin, and I am available to work on developing the `claimMessage` functionality for pending messages. My experience includes working with JavaScript modules, integrating with blockchain services, and handling sensitive information securely.


### How I plan on tackling this issue
- **Install Dependencies**: I will start by installing `ethers.js` and the Linea SDK. These libraries are crucial for interacting with the Ethereum blockchain and the Linea network.
## 2. Create a New JavaScript File

Create File: I will create a new JavaScript file, `claimMessage.js`, where I will implement the functionality.

## 3. Implement the Main Function

Function Implementation: In `claimMessage.js`, I will implement the function to call `claimMessage` on `L2MessageService`. This function will handle:

- Accepting the required arguments: message hash, nonce, calldata, and `L2MessageService` address.
- Interacting with the Linea SDK and ethers.js to perform the claim operation.

## 4. Secure Private Key Handling

Environment Variables: The private key will be securely managed using environment variables. I will ensure it is read securely and never exposed or logged.

```javascript
const privateKey = process.env.PRIVATE_KEY; 
```

## 5. Implement Error Handling and Logging
- Error Handling: I will incorporate robust error handling to manage any issues during the claim process, such as transaction failures or network issues.

- Logging: Logging will be implemented to track the success or failure of the claim operations for debugging and monitoring purposes.

## 6. Caveats
Private Key Security: Extra caution will be taken to ensure the private key is never exposed in logs or error messages.
Gas Price Fluctuations: I will consider gas price changes and implement handling mechanisms for transaction failures.

**Comment by adrianvrj** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hello, my name is Adrian and I have some experience with ether.js that might help me solve this isse

### How I plan on tackling this issue
Here’s a detailed plan on how I would solve this issue

1. Set Up the Project

	•	Initialize the Project: Start by creating a new Node.js project using npm init to generate a package.json file.
	•	Install Dependencies: Install the necessary dependencies:
	•	ethers.js for interacting with the Ethereum network.
	•	Linea SDK for interfacing with Linea-specific services.
	•	Optional: Install dotenv for securely managing environment variables.
	•	Set Up Environment Variables: Create a .env file to securely store sensitive information like the private key. Ensure .env is added to .gitignore to prevent it from being exposed.

2. Create the JavaScript Module

	•	Create a New File: Create a new JavaScript file, e.g., claimMessageModule.js, where the core logic will reside.
	•	Import Dependencies: Import the necessary modules (ethers, Linea SDK, and dotenv if used).
	•	Configure Environment Variables: Load environment variables securely using dotenv.config() (if applicable).

3. Implement the Main Function

	•	Setup ethers.js Provider and Wallet:
	•	Set up a provider to connect to the Ethereum network. This could be an HTTP provider or an Alchemy/Infura provider, depending on your needs.
	•	Securely load the private key from the environment variable and create a signer (wallet) using ethers.Wallet connected to the provider.
	•	Connect to L2MessageService:
	•	Accept parameters such as messageHash, nonce, calldata, and L2MessageService address.
	•	Use ethers.Contract to create a contract instance of L2MessageService.

4. Call the claimMessage Function

	•	Prepare the Function Call:
	•	Structure the function call by passing the necessary arguments like messageHash, nonce, and calldata.
	•	Consider Gas Management:
	•	Implement logic to handle gas price fluctuations. You might want to set a custom gas limit and monitor gas prices to avoid failed transactions.
	•	Handle the Transaction Response:
	•	After calling claimMessage, wait for the transaction receipt. Implement logic to track the transaction status until it’s confirmed on the blockchain.

5. Implement Secure Handling for the Private Key

	•	Secure Private Key Management:
	•	Ensure the private key is read securely from an environment variable and never hardcoded.
	•	Implement checks to prevent logging or exposing the private key.

6. Error Handling and Logging

	•	Basic Error Handling:
	•	Add try-catch blocks around key operations like the function call to claimMessage.
	•	Implement detailed logging for successful operations and errors, but ensure sensitive information like the private key is never logged.
	•	Advanced Error Handling:
	•	Consider edge cases like network failures, gas estimation errors, and revert reasons from the smart contract.
	•	Implement retry mechanisms or fallback strategies for transient errors.

7. Documentation and Best Practices

	•	Document the Code:
	•	Add comments explaining the purpose of each part of the code, especially complex logic or configurations.
	•	Follow JavaScript Best Practices:
	•	Ensure the code is clean, readable, and follows JavaScript best practices, such as proper naming conventions and modularization.
	•	Security Considerations:
	•	Double-check that sensitive data like private keys are never exposed.
	•	Consider using tools like eslint or prettier for consistent code style.

**Comment by DIWAKARKASHYAP** [comment]
i want to work on this issue
